name: Release helm chart
'on':
  push:
    tags:
    - v*.*.*
  workflow_dispatch: null
jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0
    - name: Set output
      id: vars
      run: echo "tag=$(git describe --tags)" >> $GITHUB_OUTPUT
    - name: Release Helm
      run: "echo ${{ secrets.GH_PAT }} | helm registry login ghcr.io -u ${{ github.repository_owner\
        \ }} --password-stdin\nexport APP_VERSION=${{ steps.vars.outputs.tag }}\n\
        export HELM_VERSION=${{ steps.vars.outputs.tag }}\nexport HELM_REPO=ghcr.io/${{\
        \ github.repository_owner }}\nif [[ ! \"$line\" =~ ^v ]]\nthen\n  unset APP_VERSION\n\
        \  unset HELM_VERSION\nfi\nhelm dependency update files/helm/fastgpt\nhelm\
        \ package files/helm/fastgpt --version ${HELM_VERSION}-helm --app-version\
        \ ${APP_VERSION} -d bin\nhelm push bin/fastgpt-${HELM_VERSION}-helm.tgz oci://${HELM_REPO}\n"
